version: "3.8"

services:
  cb-be:
    container_name: cb-be
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
    external: true
